/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:9cf0cb09-7fdf-4314-a8f0-24bfa5b0afdd",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_PaMoFay2I",
    "aws_user_pools_web_client_id": "6u6gj2sbumcmnlt3oeeb8bg455",
    "oauth": {}
};


export default awsmobile;
